# Basics of Python Syntax
2018-08-25


In [54]:
# Other system information retrivals
# 1.import sys
#print(sys.version)
# 2. import numexpr
#numexpr.print_versions()

%load_ext version_information
%version_information

#magic list * time is useful
#%lsmagic

The version_information extension is already loaded. To reload it, use:
  %reload_ext version_information


Software versions
Python 3.6.5 64bit [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
IPython 6.4.0
OS Darwin 17.7.0 x86_64 i386 64bit
Tue Aug 28 08:48:56 2018 PDT

## 1. Basic Syntax
Exponetial
ex:

In [55]:
4**2

16

Remaider of the division

In [56]:
18%7

4

### Python Types

-Converting [Converting Data Types](https://www.digitalocean.com/community/tutorials/how-to-convert-data-types-in-python-3)

- **Strings**

In [57]:
x = 'years'
print(type(x))
print(x)

<class 'str'>
years


- converting to strings

In [58]:
string = str(2)
print(type(string))
print(string)

<class 'str'>
2


- String can be added

In [59]:
y = 'my '

print(y + x)

my years


- **Interger**
 - An integer (more commonly called an int) is a number without a decimal point.

-Converting to interger

In [60]:
interger = int(2)
print(interger)
type(interger)

2


int

- **Float**
 - A float is a floating-point number, which means it is a number that has a decimal place

In [61]:
float = 1.2
print(float)

1.2


##  2. Python Lists
1. list
2. sub-list

In [62]:
my_list = ['me', 1.3, 'you', 2.0, 'variable', 5.0 ]
sub_list = [['me', 10], ['you', 5.0]]
print(my_list)
print(sub_list)

['me', 1.3, 'you', 2.0, 'variable', 5.0]
[['me', 10], ['you', 5.0]]


### Subsetting lists
- index start from 0, 1, 2, ...

- 2 types of selecting from list

In [63]:
my_list[4]

'variable'

In [64]:
my_list[-2]

'variable'

- List slicing
 - does **not** include number after the colon
 - [ Start : End]

In [65]:
my_list[2:4]

['you', 2.0]

- Summing within list

In [66]:
sum_list = my_list[1] + my_list[3]
print(sum_list)

3.3


- Selecting massively
 - [:end]
 - [start:]

In [67]:
my_list[:2]

['me', 1.3]

### Change List Elements
- change it to ME and 100

In [68]:
my_list[:2] = ['ME', 100.0]
print(my_list)

['ME', 100.0, 'you', 2.0, 'variable', 5.0]


### Adding and Removing Elements

1. Adding element

In [69]:
update_my_list = my_list + ['him', 8.0]
print(update_my_list)

['ME', 100.0, 'you', 2.0, 'variable', 5.0, 'him', 8.0]


2. Removing element

In [70]:
del(update_my_list[6:])
print(update_my_list)

['ME', 100.0, 'you', 2.0, 'variable', 5.0]


### Updating Lists

1. Implicit update

In [71]:
my_list_copy=my_list
print(my_list_copy)
my_list_copy[2]="YOU"
print(my_list_copy)

['ME', 100.0, 'you', 2.0, 'variable', 5.0]
['ME', 100.0, 'YOU', 2.0, 'variable', 5.0]


 - Also changes the original list
  - 'YOU' for my_list

In [72]:
print(my_list)

['ME', 100.0, 'YOU', 2.0, 'variable', 5.0]


2. Explicit Update

In [73]:
my_list_copy_explicit= list(my_list)


or

In [74]:
my_list_copy_explicit_slicing=my_list[:]

In [75]:
my_list_copy_explicit[4]="VARIABLE"
print(my_list_copy_explicit)
my_list_copy_explicit_slicing[4]="VARIABLE"
print(my_list_copy_explicit_slicing)
print(my_list)

['ME', 100.0, 'YOU', 2.0, 'VARIABLE', 5.0]
['ME', 100.0, 'YOU', 2.0, 'VARIABLE', 5.0]
['ME', 100.0, 'YOU', 2.0, 'variable', 5.0]


## 3. Funtions and Packages

1. Max() - returns the max value form the list

In [76]:
float_list=[12,90,55,100,40]
max(float_list)

100

2. round() (number, digits on presition)

In [77]:
round(12.678,2)

12.68

In [78]:
round(12.678)

13

3. len()

In [79]:
len('hellooo')

7

4. sorted() - 3 arguments iterable, key and reverse

In [80]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



### Built-in Funtions
#### Methods (specific to python objects)

##### List methods

1. index -return the value in the list

In [81]:
my_list.index('YOU')

2

2. Count() - returns the count from the list

In [82]:
my_list.count('YOU')

1

3. Capitalize - capitalizes the first letter
 - other capitalization [Other Capitalizations](https://stackoverflow.com/questions/352478/capitalize-a-string)

In [83]:
worker = 'my'
worker.capitalize()


'My'

4. Replace

In [84]:
worker.replace('y', 'e')

'me'

5. Append on lists

In [85]:
my_list.append('new')
print(my_list)

['ME', 100.0, 'YOU', 2.0, 'variable', 5.0, 'new']


### Packages - Directory of python scripts ex -mod1.py
1. Numpy - for arrays
2. Matplotlib - data visualization
3. Scikit-learn - machine learning
 - Use Terminal 
  - pip3 install Package Name

## 4. Numpy (numeric python)
Allows you to do calculation over entire arrays

1. Create an array from list only floats or intergers
 - np.array(name of list)

In [86]:
import numpy as np

#creating list with floats only

hours=[2.3, 4.0, 8.1, 9.0, 7.8 ]

np_hours= np.array(hours)
print(np_hours)

[2.3 4.  8.1 9.  7.8]


### Numpy Differences

Calculating: Multiplying times 2

In [87]:
calc_np_hours= np_hours*2
print(calc_np_hours)

[ 4.6  8.  16.2 18.  15.6]


Differences in List and Arrays

In [88]:
hours + hours

[2.3, 4.0, 8.1, 9.0, 7.8, 2.3, 4.0, 8.1, 9.0, 7.8]

In [89]:
np_hours + np_hours

array([ 4.6,  8. , 16.2, 18. , 15.6])

### Numpy Subsetting

In [90]:
np_hours[1]

4.0

using math expressions

In [91]:
np_hours > 8

array([False, False,  True,  True, False])

### 2D NumPy Array

In [93]:
np_2d = np.array([[2.0, 3.5, 6.6, 7.6, 8.0], [3.5, 10.0, 8.8, 9.0, 5.5]])

Code to know the shape of array

In [94]:
np_2d.shape

(2, 5)

##### Subsetting 2D NumPy Arrays

In [95]:
np_2d[0]

array([2. , 3.5, 6.6, 7.6, 8. ])

1. [row] [collumn]

In [96]:
np_2d[0][3]

7.6

2. [row, collumn]

In [97]:
np_2d[0,3]

7.6

In [98]:
np_2d[:,1:3]

array([[ 3.5,  6.6],
       [10. ,  8.8]])

### Numpy: Basic Statistics

##### Average

In [99]:
np.mean(np_2d)

6.45

Average for one row

In [100]:
np.mean(np_2d[0,:])

5.54

###### Median

In [101]:
np.median(np_2d)

7.1

In [102]:
np.median(np_2d[0,:])

6.6

###### Correlation

In [104]:
np.corrcoef(np_2d[0,:], np_2d[1,:])

array([[1.        , 0.29595853],
       [0.29595853, 1.        ]])

###### Standard Deviation

In [106]:
np.std(np_2d[0,:])

2.371160053644629

###### Sum

###### Sort

###### Random

np.random.normal(mean, stdv, number of samples)

In [107]:
weekh= np.round(np.random.normal(8,2.0,100),2)

In [108]:
print(weekh)

[ 9.4   7.87  8.25  9.31  7.83  6.96 11.89  6.22  8.08  5.62 10.03  7.27
  7.54  8.73 10.32  8.29 11.77  5.96  5.01  7.27  9.32 10.55 11.48 10.79
  8.4   6.9   7.07  6.02  8.7  10.85  5.18  4.06  7.98  7.04  6.5   7.97
  7.91  7.09  6.98  9.48  7.09  8.27  3.54  7.64 10.55  6.92  7.47  7.46
  3.33  5.48  7.46 10.35  5.38  8.94  5.85  9.74  9.24 12.01  8.97 11.39
  9.33  7.53  7.    7.33  8.5   5.17  8.37  4.39  6.51  4.84  8.98  7.5
  8.07  6.69  8.28  6.49  6.28  7.56  9.69  7.41  9.94  7.27  7.51  8.62
  9.93  5.71 11.87 10.81  8.47  6.65  8.42 10.62  9.57  7.92  7.37  8.65
  7.08  8.74  4.54  8.68]


In [114]:
weeklunch = np.round(np.random.normal(1,.25,100),2)
print(weeklunch)

[1.03 0.81 1.12 0.47 0.84 1.09 1.31 0.95 0.96 0.94 1.03 0.93 1.19 1.12
 1.19 0.9  0.78 0.9  0.62 1.03 1.11 0.96 0.95 1.38 1.26 1.41 0.66 0.7
 1.09 1.43 0.85 0.81 1.05 0.86 1.15 0.96 0.9  0.79 1.17 0.97 1.13 1.28
 1.13 1.3  1.24 0.84 0.97 0.92 1.09 0.84 0.82 0.78 0.99 1.24 1.38 1.27
 0.93 1.16 1.28 1.12 0.83 0.9  1.35 1.02 0.91 1.23 0.8  1.13 1.28 0.66
 0.7  1.06 1.06 1.33 1.17 1.15 1.46 0.99 1.32 0.93 0.59 0.61 1.13 0.53
 0.64 1.2  0.79 0.92 0.94 1.01 1.22 0.88 1.24 1.1  0.94 0.9  0.5  1.27
 0.94 0.22]


Code created to generated lables for days of the week for 100 days
 - Logic: 100 days/5days a week = 20 weeks

In [132]:
daysofweek = ['mo', 'we', 'tu', 'th', 'fr']
hdaysofweek = daysofweek *20
print(hdaysofweek)
np_hdaysofweek = np.array(hdaysofweek)

['mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr', 'mo', 'we', 'tu', 'th', 'fr']


Code to generate random choices from list or 1d array
 - random.choice(variable or list, times, probablilitis each element in list or array * must sum to 1)

In [127]:
np_daysofweek =np.random.choice(daysofweek, 100, p=[.2, .2, .2, .2, .2])
print(np_daysofweek)

['tu' 'tu' 'we' 'mo' 'fr' 'th' 'mo' 'mo' 'tu' 'th' 'fr' 'mo' 'tu' 'we'
 'we' 'mo' 'mo' 'mo' 'we' 'we' 'mo' 'tu' 'tu' 'tu' 'we' 'fr' 'fr' 'we'
 'th' 'fr' 'th' 'mo' 'th' 'mo' 'tu' 'th' 'mo' 'we' 'th' 'th' 'fr' 'tu'
 'we' 'mo' 'we' 'th' 'mo' 'fr' 'th' 'fr' 'tu' 'tu' 'tu' 'we' 'th' 'mo'
 'th' 'tu' 'mo' 'tu' 'th' 'th' 'mo' 'mo' 'tu' 'tu' 'mo' 'fr' 'th' 'fr'
 'mo' 'tu' 'tu' 'mo' 'th' 'fr' 'mo' 'tu' 'mo' 'fr' 'th' 'we' 'we' 'th'
 'th' 'we' 'fr' 'tu' 'th' 'mo' 'tu' 'tu' 'fr' 'fr' 'fr' 'th' 'th' 'tu'
 'we' 'th']


##### Stack - Merge
use astype(np.object) after array to keep as float

In [195]:
np_workday= np.column_stack((np_hdaysofweek, weekh.astype(np.object), weeklunch.astype(np.object)))
print(np_workday)

[['mo' 9.4 1.03]
 ['we' 7.87 0.81]
 ['tu' 8.25 1.12]
 ['th' 9.31 0.47]
 ['fr' 7.83 0.84]
 ['mo' 6.96 1.09]
 ['we' 11.89 1.31]
 ['tu' 6.22 0.95]
 ['th' 8.08 0.96]
 ['fr' 5.62 0.94]
 ['mo' 10.03 1.03]
 ['we' 7.27 0.93]
 ['tu' 7.54 1.19]
 ['th' 8.73 1.12]
 ['fr' 10.32 1.19]
 ['mo' 8.29 0.9]
 ['we' 11.77 0.78]
 ['tu' 5.96 0.9]
 ['th' 5.01 0.62]
 ['fr' 7.27 1.03]
 ['mo' 9.32 1.11]
 ['we' 10.55 0.96]
 ['tu' 11.48 0.95]
 ['th' 10.79 1.38]
 ['fr' 8.4 1.26]
 ['mo' 6.9 1.41]
 ['we' 7.07 0.66]
 ['tu' 6.02 0.7]
 ['th' 8.7 1.09]
 ['fr' 10.85 1.43]
 ['mo' 5.18 0.85]
 ['we' 4.06 0.81]
 ['tu' 7.98 1.05]
 ['th' 7.04 0.86]
 ['fr' 6.5 1.15]
 ['mo' 7.97 0.96]
 ['we' 7.91 0.9]
 ['tu' 7.09 0.79]
 ['th' 6.98 1.17]
 ['fr' 9.48 0.97]
 ['mo' 7.09 1.13]
 ['we' 8.27 1.28]
 ['tu' 3.54 1.13]
 ['th' 7.64 1.3]
 ['fr' 10.55 1.24]
 ['mo' 6.92 0.84]
 ['we' 7.47 0.97]
 ['tu' 7.46 0.92]
 ['th' 3.33 1.09]
 ['fr' 5.48 0.84]
 ['mo' 7.46 0.82]
 ['we' 10.35 0.78]
 ['tu' 5.38 0.99]
 ['th' 8.94 1.24]
 ['fr' 5.85 1.38]
 ['mo' 9.7

Generated filter monday work hours with 2 different lists

In [151]:
mondaywork= weekh[np_hdaysofweek == 'mo']
print(mondaywork)

[ 9.4   6.96 10.03  8.29  9.32  6.9   5.18  7.97  7.09  6.92  7.46  9.74
  9.33  5.17  8.98  6.49  9.94  5.71  8.42  8.65]


Generated filter for monday using the stacked array and array of days of the week
 - must use array with same length

In [196]:
mowork = np_workday[np_hdaysofweek == 'mo', 1]
print(mowork)

[9.4 6.96 10.03 8.29 9.32 6.9 5.18 7.97 7.09 6.92 7.46 9.74 9.33 5.17 8.98
 6.49 9.94 5.71 8.42 8.65]


In [207]:
print("Average work hour on Monday: " + str(round(np.mean(mowork),2)))

Average work hour on Monday: 7.9
