# Basics of Python Syntax
2018-08-25


In [3]:
# Other system information retrivals
# 1.import sys
#print(sys.version)
# 2. import numexpr
#numexpr.print_versions()

%load_ext version_information
%version_information

#magic list * time is useful
#%lsmagic

Software versions
Python 3.6.5 64bit [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
IPython 6.4.0
OS Darwin 17.7.0 x86_64 i386 64bit
Mon Aug 27 13:23:21 2018 PDT

## 1. Basic Syntax
Exponetial
ex:

In [4]:
4**2

16

Remaider of the division

In [5]:
18%7

4

### Python Types

-Converting [Converting Data Types](https://www.digitalocean.com/community/tutorials/how-to-convert-data-types-in-python-3)

- **Strings**

In [6]:
x = 'years'
print(type(x))
print(x)

<class 'str'>
years


- converting to strings

In [7]:
string = str(2)
print(type(string))
print(string)

<class 'str'>
2


- String can be added

In [8]:
y = 'my '

print(y + x)

my years


- **Interger**
 - An integer (more commonly called an int) is a number without a decimal point.

-Converting to interger

In [9]:
interger = int(2)
print(interger)
type(interger)

2


int

- **Float**
 - A float is a floating-point number, which means it is a number that has a decimal place

In [10]:
float = 1.2
print(float)

1.2


##  2. Python Lists
1. list
2. sub-list

In [11]:
my_list = ['me', 1.3, 'you', 2.0, 'variable', 5.0 ]
sub_list = [['me', 10], ['you', 5.0]]
print(my_list)
print(sub_list)

['me', 1.3, 'you', 2.0, 'variable', 5.0]
[['me', 10], ['you', 5.0]]


### Subsetting lists
- index start from 0, 1, 2, ...

- 2 types of selecting from list

In [12]:
my_list[4]

'variable'

In [13]:
my_list[-2]

'variable'

- List slicing
 - does **not** include number after the colon
 - [ Start : End]

In [14]:
my_list[2:4]

['you', 2.0]

- Summing within list

In [15]:
sum_list = my_list[1] + my_list[3]
print(sum_list)

3.3


- Selecting massively
 - [:end]
 - [start:]

In [16]:
my_list[:2]

['me', 1.3]

### Change List Elements
- change it to ME and 100

In [17]:
my_list[:2] = ['ME', 100.0]
print(my_list)

['ME', 100.0, 'you', 2.0, 'variable', 5.0]


### Adding and Removing Elements

1. Adding element

In [18]:
update_my_list = my_list + ['him', 8.0]
print(update_my_list)

['ME', 100.0, 'you', 2.0, 'variable', 5.0, 'him', 8.0]


2. Removing element

In [19]:
del(update_my_list[6:])
print(update_my_list)

['ME', 100.0, 'you', 2.0, 'variable', 5.0]


### Updating Lists

1. Implicit update

In [20]:
my_list_copy=my_list
print(my_list_copy)
my_list_copy[2]="YOU"
print(my_list_copy)

['ME', 100.0, 'you', 2.0, 'variable', 5.0]
['ME', 100.0, 'YOU', 2.0, 'variable', 5.0]


 - Also changes the original list
  - 'YOU' for my_list

In [21]:
print(my_list)

['ME', 100.0, 'YOU', 2.0, 'variable', 5.0]


2. Explicit Update

In [22]:
my_list_copy_explicit= list(my_list)


or

In [23]:
my_list_copy_explicit_slicing=my_list[:]

In [24]:
my_list_copy_explicit[4]="VARIABLE"
print(my_list_copy_explicit)
my_list_copy_explicit_slicing[4]="VARIABLE"
print(my_list_copy_explicit_slicing)
print(my_list)

['ME', 100.0, 'YOU', 2.0, 'VARIABLE', 5.0]
['ME', 100.0, 'YOU', 2.0, 'VARIABLE', 5.0]
['ME', 100.0, 'YOU', 2.0, 'variable', 5.0]


## 3. Funtions and Packages

1. Max() - returns the max value form the list

In [25]:
float_list=[12,90,55,100,40]
max(float_list)

100

2. round() (number, digits on presition)

In [26]:
round(12.678,2)

12.68

In [27]:
round(12.678)

13

3. len()

In [28]:
len('hellooo')

7

4. sorted() - 3 arguments iterable, key and reverse

In [29]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



### Built-in Funtions
#### Methods (specific to python objects)

##### List methods

1. index -return the value in the list

In [30]:
my_list.index('YOU')

2

2. Count() - returns the count from the list

In [31]:
my_list.count('YOU')

1

3. Capitalize - capitalizes the first letter
 - other capitalization [Other Capitalizations](https://stackoverflow.com/questions/352478/capitalize-a-string)

In [32]:
worker = 'my'
worker.capitalize()


'My'

4. Replace

In [33]:
worker.replace('y', 'e')

'me'

5. Append on lists

In [34]:
my_list.append('new')
print(my_list)

['ME', 100.0, 'YOU', 2.0, 'variable', 5.0, 'new']


### Packages - Directory of python scripts ex -mod1.py
1. Numpy - for arrays
2. Matplotlib - data visualization
3. Scikit-learn - machine learning
 - Use Terminal 
  - pip3 install Package Name

## 4. Numpy (numeric python)
Allows you to do calculation over entire arrays

1. Create an array from list only floats or intergers
 - np.array(name of list)

In [47]:
import numpy as np

#creating list with floats only

hours=[2.3, 4.0, 8.1, 9.0, 7.8 ]

np_hours= np.array(hours)
print(np_hours)

[2.3 4.  8.1 9.  7.8]


### Numpy Differences

Calculating: Multiplying times 2

In [44]:
calc_np_hours= np_hours*2
print(calc_np_hours)

[ 4.6  8.  16.2 18.  15.6]


Differences in List and Arrays

In [45]:
hours + hours

[2.3, 4.0, 8.1, 9.0, 7.8, 2.3, 4.0, 8.1, 9.0, 7.8]

In [46]:
np_hours + np_hours

array([ 4.6,  8. , 16.2, 18. , 15.6])

### Numpy Subsetting

In [48]:
np_hours[1]

4.0

using math expressions

In [49]:
np_hours > 8

array([False, False,  True,  True, False])